import type { NextPage } from "next";
import Head from "next/head";
import LateralMenu from "../components/LateralMenu";
import styles from "../styles/Home.module.scss";
import { MdSearch, MdAdd } from "react-icons/md";
import Tarefa from "../components/Tarefa";
import { useState } from "react";
import ModalCreateTask from "../components/ModalCreateTask";

const Home: NextPage = () => {
  const [showModalCreate, setShowModalCreate] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>WLS | Lista de Tarefas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showModalCreate && (
        <ModalCreateTask fecharModal={() => setShowModalCreate(false)} />
      )}
      <LateralMenu />

      <main className={styles.main}>
        <section className={styles.tasksContainer}>
          <div className={styles.searchInput}>
            <MdSearch size="28" />
            <input type="text" placeholder="Procurar tarefas" />
          </div>

          <h1 className={styles.title}>Tarefas</h1>

          <ul className={styles.tasksList}>
            <Tarefa />
          </ul>

          <button className={styles.buttonNewTask} onClick={() => setShowModalCreate(true)}>
            <MdAdd size={24} />
            Nova tarefa
          </button>
        </section>
      </main>
    </div>
  );
};

export default Home;
